### PR TITLE
Adding integration Test and stage in travis for unit and integ tests

### PR DESCRIPTION
**Pull request by Pawlette**
Create an integration test for the RequestForm page, and adding new staged in travis to separate the backend tests, from the unit and integration tests.

### CODE REVIEW

**Comment by saragw6** [comment]
I think yarn.lock shouldn't be checked in but otherwise this looks good

**Comment by Pawlette** [comment]
I removed the 971bd99 commit, which shouldn't be there. Now the PR is just related with our first Integration test and creating three different stages in Travis Build for Server, Unit and Integration tests.

**Comment by austin-garrard** [comment]
@saragw6 @Pawlette `yarn.lock` should be checked in IMO. It pins the dependencies a lot more thoroughly than the package.

**Comment by saragw6** [comment]
@austin-garrard u right u right. my bad @Pawlette

**Comment by Pawlette** [comment]
All right! So, I found a small issue with our unit test, I fixed it, and I reverted the commit for deleting the lock file. I think this code is in good shape now :)

**Pull request merged**
